Fuben:
  Fuben1:
    Itemid: 31
    Child: 2
    Name: "§e§l南华山副本"
    Lores:
      - "gaga"
      - "asdweqd"
      - "fuck"
    NeedMoney: 500
    NeedItemLore: "深渊门票"
    MaxLevel: 50
    MinLevel: 20
    RestartMoney: 5000
    RestartCount: 3
  Fuben2:
    Itemid: 31
    Child: 2
    Name: "§a§l青山道副本"
    Lores:
      - "gaga"
      - "asdweqd"
      - "fuck"
    NeedMoney: 5000
    NeedItemLore: "深渊门票1"
    MaxLevel: 50
    MinLevel: 20
    RestartMoney: 5000
    RestartCount: 3
  Fuben3:
    Itemid: 31
    Child: 2
    Name: "§c§l彩虹山副本"
    Lores:
      - "彩虹山副本"
      - "asdweqd"
      - "fuck"
    NeedMoney: 5000
    NeedItemLore: "深渊门票1"
    MaxLevel: 50
    MinLevel: 20
    RestartMoney: 5000
    RestartCount: 3
  Fuben4:
    Itemid: 28
    Child: 0
    Name: "§e§l狗狗洞副本"
    Lores:
      - "gaga"
      - "asdweqd"
      - "fuck"
    NeedMoney: 5000
    NeedItemLore: "深渊门票1"
    MaxLevel: 50
    MinLevel: 20
    RestartMoney: 5000
    RestartCount: 3
FubenMenu:
  CaiDan1:
    Name: "§e§l异步活动世界"
    MenuList:
      - "Fuben1"
      - "Fuben2"
      - "Fuben3"
  CaiDan2:
    Name: "§e§l飞行地下城"
    MenuList:
      - "Fuben3"
      - "Fuben4"
LevellimitMsg: "§e§l等级不符合"
GlobalRestartCd: 10
RestartTitle: "§e§l十秒内请选择是否重生"
NoMoneyMsg: "§e§l没得鸡儿钱啊"