name: Fuben
main: com.ipedg.minecraft.Fuben
version: 1.0.0
depend: [Multiverse-Core]
commands:
  fuben:
    description: Main command for fuben.
    usage: /<command> (Startup error)
    aliases: [fb]